### ISSUE TITLE
KeyError: 'Valve' on execution.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [CorruptComputer/ProtonDB-Tags#41]
```
└─>➜⊃━☆ﾟ.*･｡ﾟ ❯  python3 ProtonDB-Tags.py --check-native
Steam found at: /home/pm/.local/share/Steam/userdata
Found user 0: anonymous   (Could not load username from Steam)
Found user 1: 150966242   PoorPocketsMcNewHold
Which user number would you like to open? 1
Selected: 
Traceback (most recent call last):
  File "/home/pm/ProtonDB-Tags/ProtonDB-Tags.py", line 335, in <module>
    main(ARGUMENTS)
  File "/home/pm/ProtonDB-Tags/ProtonDB-Tags.py", line 243, in main
    apps = sharedconfig[configstore]["Software"]["Valve"]["Steam"][get_apps_key(sharedconfig, configstore)]
KeyError: 'Valve'
```
Currently, at launch, the ProtonDB-Tags script is creating this perpetual error when launching it, either with or without the check-native argument.
I do note that I don't have any other accounts logged into Steam.
[sharedconfig.vdf.txt](https://github.com/CorruptComputer/ProtonDB-Tags/files/7112201/sharedconfig.vdf.txt)

**Comment by CorruptComputer** [comment]
Thanks for opening the issue. It looks like in your case the keys are `"valve"` and `"steam"` instead of `"Valve"` and `"Steam"`. 
If you wanted a quick solution you could open your `sharedconfig.vdf` and just change the capitalization of those keys on lines 5 and 7. 
Sadly this project is somewhat on hold for me since my job has taken up most of my time, but if someone makes a PR to permanently fix this I would be happy to review and merge it.
